language: node_js
node_js:
  - '12'
cache:
  directories:
    - node_modules
before_deploy:
  - "npm run build"
deploy:
  - provider: pages
    github_token: $GITHUB_TOKEN
    on:
      branch: master
  - provider: npm
    email: sonquer@o2.pl
    api_key: $NPM_TOKEN
    on:
      branch: master